"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Rectangle_1 = require("./Rectangle");
var Circle_1 = require("./Circle");
var Shape_1 = require("./Shape");
var myShape = new Shape_1.Shape(10, 5);
console.log(myShape.getInfo());
var myCircle = new Circle_1.Circle(10, 12, 5);
console.log(myCircle.getInfo());
var myRectangle = new Rectangle_1.Rectangle(0, 0, 12, 15);
console.log(myRectangle.getInfo());
